operation.agentdefinition=agent.xml
operation.noconditionui=true
operation.room=ROOM
operation.conditions=
operation.hasdebugui=false
operation.envlistener=client
operation.envactor=client
operation.preprocessors=basilica2.agents.listeners.MultiModalFilter,basilica2.agents.listeners.PresenceWatcher,basilica2.agents.listeners.MessageAnnotator,basilica2.agents.listeners.RepresentationHistoryListener,basilica2.agents.listeners.RepresentationCameraListener
operation.listeners=basilica2.agents.listeners.plan.RepresentationPlanExecutor,basilica2.agents.listeners.RepresentationHistoryListener,basilica2.agents.listeners.PromptActor
