planexecutor.interstepseconds=0
planexecutor.plan_file=plans/plan_steps.xml
planexecutor.statememory=stateMemory
planexecutor.step_handlers=prompt:basilica2.agents.listeners.plan.PromptStepHandler,representation_gate:basilica2.agents.listeners.plan.RepresentationGateStepHandler,logout:basilica2.agents.listeners.plan.LogoutStepHandler
