/*
 *  Copyright (c), 2009 Carnegie Mellon University.
 *  All rights reserved.
 *  
 *  Use in source and binary forms, with or without modifications, are permitted
 *  provided that that following conditions are met:
 *  
 *  1. Source code must retain the above copyright notice, this list of
 *  conditions and the following disclaimer.
 *  
 *  2. Binary form must reproduce the above copyright notice, this list of
 *  conditions and the following disclaimer in the documentation and/or
 *  other materials provided with the distribution.
 *  
 *  Permission to redistribute source and binary forms, with or without
 *  modifications, for any purpose must be obtained from the authors.
 *  Contact Rohit Kumar (rohitk@cs.cmu.edu) for such permission.
 *  
 *  THIS SOFTWARE IS PROVIDED BY CARNEGIE MELLON UNIVERSITY ``AS IS'' AND
 *  ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 *  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 *  PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL CARNEGIE MELLON UNIVERSITY
 *  NOR ITS EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *  
 */

/*
 * ConnectionPanel.java
 *
 * Created on May 21, 2009, 5:09:48 PM
 */
package edu.cmu.cs.lti.basilica2.ui;

import edu.cmu.cs.lti.basilica2.core.Connection;
import edu.cmu.cs.lti.basilica2.core.Event;
import edu.cmu.cs.lti.basilica2.observers.ConnectionObserver;
import edu.cmu.cs.lti.basilica2.observers.ObserverEvent;
import edu.cmu.cs.lti.basilica2.ui.eventtable.EventTable;
import edu.cmu.cs.lti.basilica2.ui.eventtable.EventTableModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author rohitk
 */
public class ConnectionPanel extends javax.swing.JPanel implements ConnectionObserver {

    Connection myConnection;
    EventTable myEventTable;
    EventTableModel myEventTableModel;

    /** Creates new form ConnectionPanel */
    public ConnectionPanel(Connection c) {
        myConnection = c;
        this.setName(c.getReadableId() + ".ui.panel");
        myEventTable = new EventTable();
        myEventTableModel = new EventTableModel();
        myEventTable.setModel(myEventTableModel);
        initComponents();
        myEventTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {
                tableSelectionChanged();
            }
        });
        myConnection.addObserver(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSplitPanel = new javax.swing.JSplitPane();
        topPanel = new javax.swing.JPanel();
        eventInfoTextArea = new javax.swing.JTextArea();
        mainScroller = new javax.swing.JScrollPane(myEventTable);

        setLayout(new java.awt.BorderLayout());

        mainSplitPanel.setDividerLocation(150);
        mainSplitPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topPanel.setLayout(new java.awt.BorderLayout());

        eventInfoTextArea.setColumns(20);
        eventInfoTextArea.setLineWrap(true);
        eventInfoTextArea.setRows(5);
        eventInfoTextArea.setWrapStyleWord(true);
        topPanel.add(eventInfoTextArea, java.awt.BorderLayout.CENTER);

        mainSplitPanel.setTopComponent(topPanel);
        mainSplitPanel.setBottomComponent(mainScroller);

        add(mainSplitPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tableSelectionChanged() {
        int r = myEventTable.getSelectedRow();
        if (r != -1) {
            Event e = myEventTableModel.getEvent(r);
            this.eventInfoTextArea.setText("<event from=" + e.getSender().getName() + ">\n" + e.toString() + "\n</event>");
        } else {
            this.eventInfoTextArea.setText("");
        }
    }

    public void communicating(Connection c, Event e) {
        myEventTableModel.addRow(e);
        myEventTable.setModel(myEventTableModel);
    }

    public void inform(Connection c, String information) {
        myEventTableModel.addRow(new ObserverEvent(myConnection.getSenderComponent(), information));
        myEventTable.setModel(myEventTableModel);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea eventInfoTextArea;
    private javax.swing.JScrollPane mainScroller;
    private javax.swing.JSplitPane mainSplitPanel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
