version: '3.8'
volumes:
  mysql_data:
  shared:
    driver: local
 
services:
  nodechat:
    build:
       context: ./
       dockerfile: Dockerfile.mysql
    container_name: nodechat_lobby
    volumes:    
     - mysql_data:/var/lib/mysql
     - shared:/mysql-files 
    environment:
      MYSQL_ROOT_PASSWORD: smoot
      MYSQL_USER: "local"
      MYSQL_PASSWORD: "local"
    ports:
    - "8306:3306"
    - "8500:8500" 
    networks:
    - bazaar-net
  bazaar:
    build: 
       context: ./
       dockerfile: Dockerfile
    container_name: bazaar_lobby
    depends_on:
     - nodechat
    ports:
     - "8000:8000"
     - "8001:8001"
     - "8300:443"
     - "8400:444"
     - "5555:5555"
    volumes:
     - shared:/mysql-files
     - ./agents:/usr/bazaar/agents
     - ../../LightSide:/usr/bazaar/LightSide
     - ./lobby/html_pages:/usr/bazaar/lobby/html_pages
     - ./bazaar:/usr/bazaar/bazaar
    networks:
    - bazaar-net
networks:
  bazaar-net:
    driver: bridge
