openai.api.key=
llama2.api.key=

model=openai
name=DocBot
openai.request.url=https://api.openai.com/v1/chat/completions
openai.model.name=gpt-5.5
openai.temperature=1
openai.context.length=10
openai.context.flag=true
openai.prompt.context="Check the grammar of every complete sentence in the text that you have not already checked. A complete sentence is defined as a string one or more words without a line break ending with a period, question mark, or exclamation mark. Provide a list of all sentences that you have not previously checked that contain grammar errors.  Do not report an error more than once. For each sentence with an unreported error, provide a corrected version of the sentence.  If there are no grammar errors that have not already been reported, respond with 'No grammar errors found.'"